export const alphabetImages: Record<string, number> = {
    A: require("../assets/Alphabet/Images/Apple.png"),
    B: require("./Alphabet/Images/Balloons.png"),
    C: require("../assets/Alphabet/Images/Car.png"),
    D: require("../assets/Alphabet/Images/Drum.png"),
    E: require("../assets/Alphabet/Images/Egg.png"),
    F: require("../assets/Alphabet/Images/Flower.png"),
    G: require("../assets/Alphabet/Images/Guitar.png"),
    H: require("../assets/Alphabet/Images/Hotdog.png"),
    I: require("../assets/Alphabet/Images/Igloo.png"),
    J: require("../assets/Alphabet/Images/Jam.png"),
    K: require("../assets/Alphabet/Images/Kite.png"),
    L: require("../assets/Alphabet/Images/Leaf.png"),
    M: require("../assets/Alphabet/Images/Moon.png"),
    N: require("../assets/Alphabet/Images/Nest.png"),
    O: require("../assets/Alphabet/Images/Orange.png"),
    P: require("../assets/Alphabet/Images/Penguin.png"),
    Q: require("../assets/Alphabet/Images/Queen.png"),
    R: require("../assets/Alphabet/Images/Rainbow.png"),
    S: require("../assets/Alphabet/Images/Sun.png"),
    T: require("../assets/Alphabet/Images/Tree.png"),
    U: require("../assets/Alphabet/Images/Umbrella.png"),
    V: require("../assets/Alphabet/Images/Violin.png"),
    W: require("../assets/Alphabet/Images/Whale.png"),
    X: require("../assets/Alphabet/Images/Xray.png"),
    Y: require("../assets/Alphabet/Images/Yarn.png"),
    Z: require("../assets/Alphabet/Images/Zip.png"),
};

export const alphabetLetters: Record<string, number> = {
    A: require("../assets/Alphabet/Letters/A.png"),
    B: require("../assets/Alphabet/Letters/B.png"),
    C: require("../assets/Alphabet/Letters/C.png"),
    D: require("../assets/Alphabet/Letters/D.png"),
    E: require("../assets/Alphabet/Letters/E.png"),
    F: require("../assets/Alphabet/Letters/F.png"),
    G: require("../assets/Alphabet/Letters/G.png"),
    H: require("../assets/Alphabet/Letters/H.png"),
    I: require("../assets/Alphabet/Letters/I.png"),
    J: require("../assets/Alphabet/Letters/J.png"),
    K: require("../assets/Alphabet/Letters/K.png"),
    L: require("../assets/Alphabet/Letters/L.png"),
    M: require("../assets/Alphabet/Letters/M.png"),
    N: require("../assets/Alphabet/Letters/N.png"),
    O: require("../assets/Alphabet/Letters/O.png"),
    P: require("../assets/Alphabet/Letters/P.png"),
    Q: require("../assets/Alphabet/Letters/Q.png"),
    R: require("../assets/Alphabet/Letters/R.png"),
    S: require("../assets/Alphabet/Letters/S.png"),
    T: require("../assets/Alphabet/Letters/T.png"),
    U: require("../assets/Alphabet/Letters/U.png"),
    V: require("../assets/Alphabet/Letters/V.png"),
    W: require("../assets/Alphabet/Letters/W.png"),
    X: require("../assets/Alphabet/Letters/X.png"),
    Y: require("../assets/Alphabet/Letters/Y.png"),
    Z: require("../assets/Alphabet/Letters/Z.png"),
};

export const numberImages: Record<string, number> = {
    1: require("../assets/Numbers/Digits/1.png"),
    2: require("../assets/Numbers/Digits/2.png"),
    3: require("../assets/Numbers/Digits/3.png"),
    4: require("../assets/Numbers/Digits/4.png"),
    5: require("../assets/Numbers/Digits/5.png"),
    6: require("../assets/Numbers/Digits/6.png"),
    7: require("../assets/Numbers/Digits/7.png"),
    8: require("../assets/Numbers/Digits/8.png"),
    9: require("../assets/Numbers/Digits/9.png"),
    10: require("../assets/Numbers/Digits/10.png"),
    11: require("../assets/Numbers/Digits/11.png"),
    12: require("../assets/Numbers/Digits/12.png"),
    13: require("../assets/Numbers/Digits/13.png"),
    14: require("../assets/Numbers/Digits/14.png"),
    15: require("../assets/Numbers/Digits/15.png"),
    16: require("../assets/Numbers/Digits/16.png"),
    17: require("../assets/Numbers/Digits/17.png"),
    18: require("../assets/Numbers/Digits/18.png"),
    19: require("../assets/Numbers/Digits/19.png"),
    20: require("../assets/Numbers/Digits/20.png"),
};

export const numberDigits: Record<string, number> = {
    1: require("../assets/Numbers/Images/1-Car.png"),
    2: require("../assets/Numbers/Images/2-Shoes.png"),
    3: require("../assets/Numbers/Images/3-Guitars.png"),
    4: require("../assets/Numbers/Images/4-Icecreams.png"),
    5: require("../assets/Numbers/Images/5-Stars.png"),
    6: require("../assets/Numbers/Images/6-Eggs.png"),
    7: require("../assets/Numbers/Images/7-Bananas.png"),
    8: require("../assets/Numbers/Images/8-Crayons.png"),
    9: require("../assets/Numbers/Images/9-Spoons.png"),
    10: require("../assets/Numbers/Images/10-Apples.png"),
    11: require("../assets/Numbers/Images/11-Jellyfish.png"),
    12: require("../assets/Numbers/Images/12-Hats.png"),
    13: require("../assets/Numbers/Images/13-Balloons.png"),
    14: require("../assets/Numbers/Images/14-Socks.png"),
    15: require("../assets/Numbers/Images/15-Trees.png"),
    16: require("../assets/Numbers/Images/16-Penguins.png"),
    17: require("../assets/Numbers/Images/17-Shells.png"),
    18: require("../assets/Numbers/Images/18-Sweets.png"),
    19: require("../assets/Numbers/Images/19-Books.png"),
    20: require("../assets/Numbers/Images/20-Cupcakes.png"),
};

export const alphabetSounds: Record<string, number> = {
    A: require("../assets/Sounds/Letters/A.m4a"),
    B: require("../assets/Sounds/Letters/B.m4a"),
    C: require("../assets/Sounds/Letters/C.m4a"),
    D: require("../assets/Sounds/Letters/D.m4a"),
    E: require("../assets/Sounds/Letters/E.m4a"),
    F: require("../assets/Sounds/Letters/F.m4a"),
    G: require("../assets/Sounds/Letters/G.m4a"),
    H: require("../assets/Sounds/Letters/H.m4a"),
    I: require("../assets/Sounds/Letters/I.m4a"),
    J: require("../assets/Sounds/Letters/J.m4a"),
    K: require("../assets/Sounds/Letters/K.m4a"),
    L: require("../assets/Sounds/Letters/L.m4a"),
    M: require("../assets/Sounds/Letters/M.m4a"),
    N: require("../assets/Sounds/Letters/N.m4a"),
    O: require("../assets/Sounds/Letters/O.m4a"),
    P: require("../assets/Sounds/Letters/P.m4a"),
    Q: require("../assets/Sounds/Letters/Q.m4a"),
    R: require("../assets/Sounds/Letters/R.m4a"),
    S: require("../assets/Sounds/Letters/S.m4a"),
    T: require("../assets/Sounds/Letters/T.m4a"),
    U: require("../assets/Sounds/Letters/U.m4a"),
    V: require("../assets/Sounds/Letters/V.m4a"),
    W: require("../assets/Sounds/Letters/W.m4a"),
    X: require("../assets/Sounds/Letters/X.m4a"),
    Y: require("../assets/Sounds/Letters/Y.m4a"),
    Z: require("../assets/Sounds/Letters/Z.m4a"),
};

export const numberSounds: Record<string, number> = {
    1: require("../assets/Sounds/Numbers/1.m4a"),
    2: require("../assets/Sounds/Numbers/2.m4a"),
    3: require("../assets/Sounds/Numbers/3.m4a"),
    4: require("../assets/Sounds/Numbers/4.m4a"),
    5: require("../assets/Sounds/Numbers/5.m4a"),
    6: require("../assets/Sounds/Numbers/6.m4a"),
    7: require("../assets/Sounds/Numbers/7.m4a"),
    8: require("../assets/Sounds/Numbers/8.m4a"),
    9: require("../assets/Sounds/Numbers/9.m4a"),
    10: require("../assets/Sounds/Numbers/10.m4a"),
    11: require("../assets/Sounds/Numbers/11.m4a"),
    12: require("../assets/Sounds/Numbers/12.m4a"),
    13: require("../assets/Sounds/Numbers/13.m4a"),
    14: require("../assets/Sounds/Numbers/14.m4a"),
    15: require("../assets/Sounds/Numbers/15.m4a"),
    16: require("../assets/Sounds/Numbers/16.m4a"),
    17: require("../assets/Sounds/Numbers/17.m4a"),
    18: require("../assets/Sounds/Numbers/18.m4a"),
    19: require("../assets/Sounds/Numbers/19.m4a"),
    20: require("../assets/Sounds/Numbers/20.m4a"),
};

